### ISSUE TITLE
do not use events internally

### ISSUE THREAD

**Issue by rauchg** [socketio/engine.io#171]
like `once('close')` in `server.js`, since a user could call `removeAllListeners('close')`

**Comment by konstantinzolotarev** [comment]
Faced with same issue. 
I understand that it's not a real issue but mistake in code that based on engine.io. 
But if I need to remove all `close` listeners from socket using `socket.removeAllListeners('close')` it will cause a memory leak into application. Because `server.clients` would be never cleaned and connection amount wouldn't reduce after some socket closes connection.

Because of this: https://github.com/socketio/engine.io/blob/master/lib/server.js#L334

**Comment by konstantinzolotarev** [comment]
Might be it makes sense to split internal events and events that developers could rely on ? 
For example for internal use could be created `internal-close` event but for usage normal `close` event would be fired ?

**Comment by haneenmahd** [comment]
Is this issue still relevant?
