### ISSUE TITLE
nsp advisory Regular Expression Denial of Service

### ISSUE THREAD

**Issue by alecbenson** [socketio/engine.io#401]
Looks like https://nodesecurity.io/advisories/106 applies to engine.io
I think the solution is to upgrade `accepts`:

https://github.com/jshttp/accepts/releases/tag/1.3.3

**Comment by rauchg** [comment]
@alecbenson thanks for the heads-up, upgrading

**Comment by rauchg** [comment]
d9dda2b..298cb6f

**Comment by mikermcneil** [comment]
@alecbenson @rauchg Thanks!  I'll keep an eye out for the publish for engine.io and socket.io (it's pinned).

But in the mean time, for the record: this vulnerability _doesn't actually affect Socket.io or Engine.io_.  That's because Engine.io (and therefore Socket.io) is [not using `accepts` (and therefore negotiator) to check for accepted languages](https://github.com/socketio/engine.io/blob/1.6.8/lib/transports/polling.js#L300).  In other words, this is the same story as with the `compression` dependency in Sails and Connect (which @dougwilson verified this morning.)

**Comment by ChisholmKyle** [comment]
Why is accepts@1.1.4 still a dependency in engine.io npm registry tarball [https://registry.npmjs.org/engine.io/-/engine.io-1.6.11.tgz](https://registry.npmjs.org/engine.io/-/engine.io-1.6.11.tgz)? Or am I confused about npm dependency handling? See also [https://github.com/socketio/socket.io/issues/2591](https://github.com/socketio/socket.io/issues/2591)

**Comment by alokrajiv** [comment]
Snyk.io is also catching the issue and is passing the warning to many libraries that depend on engine.io:
https://snyk.io/test/npm/engine.io/1.6.11

**Comment by hairyhenderson** [comment]
This is really weird... the engine.io@1.6.11 that's installed from npm right now has accepts@1.1.4 as a dependency:

```console
$ grep accepts package.json 
    "accepts": "1.1.4",
```

Looks like 298cb6f never made it into the 1.6.11 tag:

https://github.com/socketio/engine.io/compare/1.6.11...master

**Comment by hairyhenderson** [comment]
@rauchg - would it be possible to get a 1.6.12 released with the 298cb6f fix in it?

**Comment by mavrick** [comment]
Any chance we can get this fixed?

**Comment by YasharF** [comment]
I believe the engine.io npm package needs a minor version bump to resolve the issue in the issue after the dependency upgrade.  The minor version bump would also resolve the issue with https://github.com/socketio/engine.io/issues/410

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/commit/330526a491b8fee58e7223fe874fcaa8cac1409c
