### ISSUE TITLE
Vulnerability in ws 1.1.0

### ISSUE THREAD

**Issue by cmrigney** [socketio/engine.io#410]
See https://nodesecurity.io/advisories/120

"ws" needs updated to 1.1.1 to fix it.

**Comment by 3rd-Eden** [comment]
There is no vulnerability in ws 1.1.0 - That advisory is poorly worded.  Engine.IO already fixed their vulnerablity here: https://github.com/socketio/engine.io/commit/ead9dfe206f60e1a2c60042d340601af9e2b7a1f & https://github.com/socketio/engine.io/commit/17ec2150c00e3e0e68fa6a490f940c2f4c8f11bc

**Comment by codyrigney92** [comment]
@3rd-Eden I see.  Unfortunately, [NSP](https://www.npmjs.com/package/nsp) security check will still fail since Engine.IO is using that version of the package.  I'll just add an exception for now.

**Comment by oriweingart** [comment]
+1

**Comment by hairyhenderson** [comment]
@3rd-Eden - The "vulnerability" is caused by the fact that 1.1.0 had no default `maxPayload`. It's a much safer posture to just set a sane default (which you did in 1.1.1).

IMO it's still important (and low-risk!) to update the dependency. socket.io/engine.io/etc are now considered as "insecure" by NSP, which, right or wrong, will cause a lot of nervousness among NSP users.

**Comment by sgress454** [comment]
Looks like this was patched on the [master branch](https://github.com/socketio/engine.io/commit/959c8be0cc0aa6e1be4d5021f1d83b56a157943f), and the package version was bumped to 1.6.11, but the patch didn't actually make it into the published version of 1.6.11 on NPM for some reason.  When the current code is published on NPM, this issue can be closed.

**Comment by clarkio** [comment]
For some reason when this package gets installed as a child dependency it pulls in version `1.6.11`, but still shows `ws` as `1.1.0`. My app has `socket.io` version `1.4.8` as its direct dependency here.

I'm using Node.js `v4.4.7` and npm `2.15.8`. Still digging into why this is happening, but hoping maybe someone else has come across this as well and found a fix.

**Comment by jhenriquez** [comment]
It seems it still hasn't made it into npm.

![screenshot from 2016-08-18 18-37-58](https://cloud.githubusercontent.com/assets/408459/17793139/2aa10460-6573-11e6-9de6-e50565864c0f.png)

Maybe the question is silly but is there any way I could force ws to be upgraded?

**Comment by petermikitsh** [comment]
Maybe a `1.6.12` should be released that includes the fix to NSP 120.

**Comment by clarkio** [comment]
Looking at the release commit it seems `ws` wasn't actually updated to `1.1.1` which is why it's still failing in NSP: https://github.com/socketio/engine.io/commit/10c4360bde25271279d5b1250327a7db68a1532d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R30

**Comment by hairyhenderson** [comment]
@rauchg @darrachequesne - can one of you release a 1.6.12 from the `master` branch?

**Comment by mavrick** [comment]
Can we get this patched please!

**Comment by jkomyno** [comment]
+1

**Comment by YasharF** [comment]
The dependency chain that I am running into per Snyk.io is:
socket.io@1.4.8 › socket.io-client@1.4.8 › engine.io-client@1.6.11 › ws@1.0.1

If I gathered it correctly, here are a bunch of version bumps that need to happen to close this issue:

1. https://github.com/socketio/engine.io-client/blob/master/package.json , engine.io-client has the new version of ws, but needs a minor version bump for the npm package to be updated (aka to 1.6.12)
2. Once the above change (1) is done, https://github.com/socketio/socket.io-client/blob/master/package.json will need to pick up 1.6.12 of engine.io-client, and also get at least a minor version bump (aka to 1.4.9)
3. Once the above change (2) is done, https://github.com/socketio/socket.io/blob/master/package.json needs to pick up the new version of socket.io-client (aka 1.4.9) and have a minor version bump (aka to 1.4.9)

**Comment by andresmatasuarez** [comment]
+1

**Comment by petermikitsh** [comment]
We should also clarify that there is real value added in getting this fix available to package users. As mentioned in [NSP-120](https://nodesecurity.io/advisories/120), bad actors will be able to repeatedly crash your node process through continually sending large requests. Being able to rather easily threaten the availability of an application is a serious matter, and it's one that shouldn't be taken lightly. It has been some time since the initial report, but a patch is better late than never.

**Comment by rsp** [comment]
@rauchg @darrachequesne Since this issue has already been addressed several months ago, is there any chance that someone will run: `npm version patch && npm publish` any time soon to close this issue? Or maybe someone has published a fork on npm that we can use in the meantime?

The ws version in dependencies was changed to 1.1.1 by @hairyhenderson in commit 959c8be0 from July 13 and it's fine on master:
https://github.com/socketio/engine.io/blob/master/package.json#L32

But the lastest version of engine.io on npm and the latest tag on GitHub is 1.6.11 from June 24 which still has ws 1.1.0 in package.json:
https://github.com/socketio/engine.io/blob/1.6.11/package.json#L30

This causes every module that uses engine.io to be marked with warnings about high severity vulnerabilities by services like Snyk: https://snyk.io/test/npm/engine.io

Since it can be fixed (and has been fixed) with a one-byte change, any ETA on publishing that change?

**Comment by YasharF** [comment]
Yes!  https://github.com/socketio/engine.io/commit/4c318ce48bb99b50a061fcc0239da7f242f90f4e

**Comment by darrachequesne** [comment]
Closed by 959c8be0cc0aa6e1be4d5021f1d83b56a157943f
