### ISSUE TITLE
Socket.writeBuffer size is not capped 

### ISSUE THREAD

**Issue by alex3d** [socketio/engine.io#420]
Socket.writeBuffer size is not capped, so malicious client can trigger out of memory error on the socket.io server (at least with websocket transport).
I can provide vulnerability POC on request.

**Comment by darrachequesne** [comment]
@alex3d hi! Could you provide the said POC please? Besides, any idea how to fix?

**Comment by darrachequesne** [comment]
Thanks, I could reproduce with the POC you provided (which is basically just a client sending big buffers very quickly).

Somehow, couldn't that issue be "easily" mitigated with both the `maxPayload` option (which is `the maximum allowed message size in bytes`, [ref](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketserveroptions-callback)) and some rate-limiter which will limit the number of bytes per second a given socket can send (and close it)?

**Comment by Dynalon** [comment]
I want to re-open this as I think this is still not fixed. I was just examining the engineio code, and it seems `writeBuffer` in `socket.js` is just an [unbound array](https://github.com/socketio/engine.io/blob/master/lib/socket.js#L27) serving as a queue, holding an arbitrary amount of packets without any limit.

Packets are added to the `writeBuffer` via the [sendPacket](https://github.com/socketio/engine.io/blob/master/lib/socket.js#L401) function, not checking for a maximum amount of packages already in queue. The `writeBuffer` is flushed explicity, or after the `drain` event happens in a transport (which ultimately is an event triggered by the kernel that will tell you that the tcp write buffer has become available for writing again).

The scenario to produce a DoS attack should be very easy to setup:

1. Setup a client (receiver) and throttle the websocket tcp connections to very low amount (just enough so the tcp connection wont breakdown, i.e. 1kb/sec) using os-level tools for network throttling (on linux i.e. using `iptables` in conjunction with `tc`). Due to the nature of TCP flow control, the engineio server will not send more data to the client as it can receive which is ~1kb/sec.
1. Setup a malicous client (sender) that sends data to this throttled client via an engineio server as intermediary, sending as much data as possible.

The result should be that the `writeBuffer` is written at roughly the same speed as the sender network speed (depends on enabled packet compression). In ordinary setups with V8 memory limit around 1.8GB per process, you should be able to fill up all the server process memory in less than a minute using a 1 Gbit/s link, and only a few minutes using a 100 Mbit/s link.

To fix this, a maximum packet limit has to be set for `writeBuffer` and the API should be able to emit errors when the limit is reached (in which case the .send() has to error on the API consumer side).

**Comment by yang** [comment]
@darrachequesne Limiting message size and rate only delay the issue—a client who isn't reading packets can still cause your server to consume memory unbounded.  Also, cutting these down isn't applicable to all applications.

**Comment by Dynalon** [comment]
@darrachequesne @yang I did some thinking and comparison and have come to the conclusion that the only way to be safe is to buffer a limited amount of packets, and then drop the client/receiver (=disconnect the socket) if he can not keep up receiving. This is [how redis pubsub is implemented](https://stackoverflow.com/questions/27745842/redis-pubsub-and-message-queueing). 

If one would throttle the *sending* client, a single receiver can throttle broadcast frequency for potentially thousand of other users. If we drop (=disconnect) the sending client, the same would hold true.

The way it is implemented right now not only introduces a DoS scenario, it might be the reason for some bad socket.io performance benchmarks. If the engineio does buffer packages forever with no limit, memory will start to fill up as soon as a *single* client cannot keep up with send frequency. Even if 1000 clients receive a broadcast packet in a timely manner, the single client who cannot keep up will eventually take all the memory of the node process (which IIRC is limited at 1.8GB in V8 by default).

A suggestion to fix this: Instead of an unbound buffer, there must be a more clever buffer queue that has a (configurable limit), or even better a soft- and a hard limit. Clients might be able to go over the soft limit (say 16 Megabytes) for a fixed amount of time to handle bursts, but once the hard limit is reached (i.e. 32 Megabytes) or the soft limit is overused for a fixed amount of time, the client must eventually be disconnected and the queue be trashed.

**Comment by darrachequesne** [comment]
@Dynalon that's an interesting idea indeed! Would you have time to send a pull request?

**Comment by Dynalon** [comment]
I dug a little into the code and wrote a middleware that can at least limit the packages per socket. I'm still trying to figure out a way to read the total byte size written to a socket, which seems not to be available in the `socket.connection` object that the middleware can access. I'll dig deeper, maybe this requires patching socketio/uws to make the byte counts available (they are available on nodes `socket` object). If you know a solution on the top of your head this would help me greatly.

Main issue is, without the byte sizes there is not way to properly handle a maximum buffer size. Implementing the rate limit as a middleware whould have the advantage that this could live out of tree, and different middlewares for different queueing strategies could be used.

**Comment by Dynalon** [comment]
As I just found out, the size of the `writeBuffer` will always be 1 at max. This is due to the async nature of nodejs which will make `socket.write()` (nodejs net.Socket, not engine/socketio socket) [always succeeds](https://nodejs.org/api/net.html#net_socket_buffersize). Therefore, the `.flush()` called in the engineio code after queueing up a packet will always succeed and the `writeBuffer` is put into the nodejs socket internal cache.

This internal cache on the socket [can be queried with .bufferSize()](https://nodejs.org/api/net.html#net_socket_buffersize) and this  is the function that we would need to read out to determine further actions (i.e. queue the packet or disconnect the client when too full). But AFAICS the original `net.Socket` from nodejs is not exposed in uws and not accessible from the middleware or even engineio level, is it?

**Comment by darrachequesne** [comment]
If I understand correctly, you want to limit the total number of bytes in the `writeBuffer` array, right? ([here](https://github.com/socketio/engine.io/blob/master/lib/socket.js#L401))

**Comment by Dynalon** [comment]
Well it does not matter where to put the limit, but somewhere down the pipeline there has to be a limiting buffer which - when full - will result the client to be disconnected. Right now I couldn't find any kind of limit neither in engineio or uws c++ code (though I just skimmed the sources), so data to a client seems to be buffered indefinetely if the client cannot keep up receiving (think TCP congestion).

In non-async world and i.e. good-old C, the `send()` command would block if the kernel TCP buffers of a socket are full, and since the process gets blocked no _receiving_ data is read from the the sender's socket; this automatically prevents memory exhaustion. This is of course not an option in 1:n messaging systems such as socketio, where a single packet (higher order socketio packet, not tcp) is saved in memory, and then relayed to multiple receiving clients. If a single client cannot keep up (=receives at a slower rate than the sender sends data) this will ultimately fill up all the memory, unless there is some kind of buffer limit which drops the slow client when reached (i.e. like redis which drops clients after a buffer limit of 32MB).

I still need more time to investigate to find out how and where data is buffered using the different transports in engineio/socketio. I could manage to get the number of bytes written/received by a socket in the middleware using the `packetCreate` and `packet` events (emitted in engines `Socket` class) looking at the `data.length` property. This at leasts helps to set ratelimits if a client is too slow or a sender sends to aggresively.
